### PR TITLE
pull request

### PR DESCRIPTION
**Pull request by Nazgand**
I updated go-gtk for this.
If you get errors with window position or lack of GtkCheckMenuItem, just update go-gtk

Also, I changed the way new files work. This is because I lost work a few times when pressing F7, F8 for reference before saving

### CODE REVIEW

**Comment by mikhailt** [comment]
I got

src/navigation.go:182: start.BackwardSearch undefined (type gtk.GtkTextIter has no field or method BackwardSearch)
src/navigation.go:186: be.BackwardSearch undefined (type gtk.GtkTextIter has no field or method BackwardSearch)

Looks like you forgot to push all the changes to go-gtk repo.

**Comment by mikhailt** [comment]
Ok, added BackwardSearch by myself and pulled your patch.
As you can see I also made some changes after that.
Here are some explanations on why I did one thing or another:

Style changes.
I strongly believe consistency is important. I use following rules: such_name_for_internal_functions and SuchForExternalOnes. Mixing these two styles is not cool like WindowEvent_cb  :D

Rejecting of names 0,1,2 for newly created files. 
It is good idea but after close consideration I decided to leave all as is. It is kind of misleading to make user feel like his changes already saved somewhere in 0 file. It is also not cool to create file with name /0, /1, etc, it is kind a hack I want to avoid. I will fix this later somehow, probably file with name "" have to always exist but not rendered in file tree.

Now about my vision of tabby. 
I dont like IDE's. I don't know a single senior developer who uses IDE's. I started writing new text editor when there are thousands of them only because only limited number of them is suitable for large projects (say 100000 files). And those who can handle big projects (codeblocks for example) all have certain number of drawbacks. You cannot use IDE with large project cause it has its own build system. So tabby is EDITOR, not IDE. I also don't want it support only Go, for example I want to use for both C and Go right now. Thats why I don't very much like injecting gofmt into menus but it is ok for now. 
About source code analysis.
This place for consideration. Probably going to implement some mechanism to formalize programming language and on top of that formalization implement symbol browser, etc regardless of this particular language.

Feel free to object, debate, propose. I'm open for that.

**Comment by Nazgand** [comment]
Proposal One: New Files
The file names made by new file could be named "New File/"+n, or "Unsaved File/"+n
One could tell anyway that they are unsaved, simply by noticing the name is not preceded by a /, and therefore cannot be on the FS. You may notice that I treated all files not starting with / as unsaved new files.

Objection One: New Files
If we have the newfile named "", then we cannot have more than one newfile at a time without losing data. This may be fine, but we would then need to add an annoying warning whenever someone tries making a new file, and asking them to save or discard previous newfile.

Proposal Two: Formatting
I believe this is a feature worth keeping, even though tabby will stay an editor. Supporting other languages is understandable, and when that happens, we could rename "Gofmt" to "Format" which would choose an appropriate way to format the file based on the language of the file.

**Comment by mikhailt** [comment]
Ok, sounds sane. 

About scripts. I want to add possibility to bind execution of arbitrary script on ctrl+f{1-12}. Probably gofmt will be in that list of scripts by default. gofmt in tools is ok for now.

Btw, do you have any feature suggestions?

**Comment by Nazgand** [comment]
Well, an auto-complete of some sort would be nice, even if it only auto-completes words that are in the same file, or all loaded files. if we go about it in such a way, then it won't matter what language the loaded files are written in. I'd like your consent on this one first though.

Another nice feature is inserting an extra tab when inserting a newline after "{", but this is trivial with Gofmt.

Also, with the newfiles, are we still going the route of ""? I will program a patch for both cases.

**Comment by mikhailt** [comment]
Autocompletion is supported by GtkSourceView widget, will be added later, not important at the moment

**Pull request merged**
